cpb_cleannode.settings:
  type: config_object
  label: 'CPB Clean Node Settings'
  mapping:
    strings_to_clean:
      type: string
      label: 'Strings to clean'
    cleaned_strings:
      type: string
      label: 'Cleaned strings'
